### PR TITLE
Local Setup for Exercises

### PR DESCRIPTION
**Pull request by HadesArchitect**
**Changes:**
- Added docker-compose.yaml to simplify local setup
- Added info to the README.md
- Adjusted preloaded notebooks RF3->RF1 (First touch, Intro to Modelling, C* Land I)
- Recorded videos for the notebooks can't be done locally. (Data Loading, Availability, App Dev Prep Statements, App Dev Accessors)
- Changed studio config to dispose old logs and snapshots/revisions

**Steps to test:**
Well, the general way to test would be to run exercises locally and do (or watch) all of them marked _CDay_ (because _info_ are, well, just _info_).
- Review docs (readme)
- Run locally
- Do exercises
- Watch videos
- Review changeset
- Report the issues

### CODE REVIEW

**Comment by HadesArchitect** [comment]
Uploading two last videos

**Comment by HadesArchitect** [comment]
FYI @clun

**Comment by HadesArchitect** [comment]
@HadesArchitect

- [x] Detailed steps to test
- [ ] Remove redundant  files (notebook logs etc.)

**Comment by SonicDMG** [comment]
I see that you shortened notebook descriptions to use "CDay" in place of "Cassandra Day". If you can't use "Cassandra Day" I would suggest to use "C*Day" if Studio allows it to denote "Cassandra" in shorthand.

**Comment by SonicDMG** [comment]
Video links in notebooks do not automatically target a new tab. I think this might be a nice to have so folks don't navigate themselves away from their notebook position.

**Comment by SonicDMG** [comment]
The "Core Cassandra Workshop: Data Loading" video here -> https://www.youtube.com/watch?v=rbHkxOTZbQ8&feature=youtu.be instructs the user to use of the nodes in their 3 node setup, but isn't this setup for folks to do this locally on their laptops? If they are doing this locally where should they perform the steps you are giving?

**Comment by SonicDMG** [comment]
Notice for video https://www.youtube.com/watch?v=rbHkxOTZbQ8&feature=youtu.be it is potato quality until around 2:25 where I can see it visibly pop to a higher quality...hard to read beforehand

**Comment by HadesArchitect** [comment]
**Review Report**

1. [x] I would suggest to use "C*Day" if Studio allows it to denote "Cassandra" in shorthand.
2. [x] Video links in notebooks do not automatically target a new tab
5. [x] Hundreds of garbage files in git (logs of studio etc.)
3. [ ] ~~The "Core Cassandra Workshop: Data Loading" video instructs the user to use of the nodes in their 3 node setup~~
4. [ ] ~~Notice for video https://www.youtube.com/watch?v=rbHkxOTZbQ8&feature=youtu.be it is potato quality until around 2:25~~

**Comment by HadesArchitect** [comment]
Unbelievable. Feedback "Video links in notebooks do not automatically target a new tab" seems to be so simple to fix, but so far it's NOT FIXABLE AT ALL.

If I use markdown, the studio's markdown interpreter is so old that it doesn't support markdown for the 'target=_blank'. If I use html, studio corrupts links (discussing in studio channel)

FYI @SonicDMG  

---
Upd. Now it's even better - embedded video!

image

**Comment by SonicDMG** [comment]
> Unbelievable. Feedback "Video links in notebooks do not automatically target a new tab" seems to be so simple to fix, but so far it's NOT FIXABLE AT ALL.
> 
> If I use markdown, the studio's markdown interpreter is so old that it doesn't support markdown for the 'target=_blank'. If I use html, studio corrupts links (discussing in studio channel)
> 
> FYI @SonicDMG
> 
> Upd. Now it's even better - embedded video!
> 
> image

Sounds like you came up with a better way to handle it, nice!

**Comment by HadesArchitect** [comment]
So far, I consider the job is done. @clun @SonicDMG Do you think it's green to merge?

**Comment by SonicDMG** [comment]
> So far, I consider the job is done. @clun @SonicDMG Do you think it's green to merge?

Yes, I'm good. I think at this point since this is the first deploy of it we can always amend changes in if we need to.

**Comment by HadesArchitect** [comment]
Ok then we always can roll back.

**Pull request merged**
